<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title><?= Config::get('SITE_NAME')?> - <?= $Title?></title>

        <link rel="stylesheet" href="<?= Config::get('SITE_URL')?>/application/views/<?= Config::get('DEFAULT_THEME')?>/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= Config::get('SITE_URL')?>/application/views/<?= Config::get('DEFAULT_THEME')?>/css/app.css" type="text/css">
    </head>

    <body>
        <div class="container" id="main">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"><?= Config::get('SITE_NAME')?> <span class="label label-primary"><?=$Title?></span></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?= Config::get('SITE_URL')?>">Main Page <span class="sr-only">(current)</span></a></li>
                        </ul>
                        <form action="<?= Config::get('SITE_URL')?>/welcome/search_note" method="post" class="navbar-form navbar-right">
                            <div class="form-group">
                                <input type="text" name="terms" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </form>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container-fluid -->
            </nav>

            <div class="sub">
                <?= require_once($child_path)?>
            </div>

        </div>

        <script src="https://code.jquery.com/jquery.js" type="text/javascript"></script>
        <script src="<?= Config::get('SITE_URL')?>/application/views/<?= Config::get('DEFAULT_THEME')?>/js/bootstrap.min.js"></script>
        <script src="<?= Config::get('SITE_URL')?>/application/views/<?= Config::get('DEFAULT_THEME')?>/js/app.js"></script>
    </body>

</html>
